# Ön Bilgiler

_İtalik_ yazmak için   _ italik _

**Kalın** yazmak için  ** kalın **

**_Hem İtalik Hem kalın_** yazmak için **_italik kalın_**


* Hücre seçimi yapıldıktan sonra;

     **a** ya basılırsa seçilen hücrenin üzerinde
   
     **b** ye basılırsa seçilen hücrenin altında yeni hücre oluşturur.


* Kopyala yapmak için Ctrl+C veya hücre simgesini seç ( [  ] ) ve sadece **C** ye bas.

* Kesme yapmak için Ctrl+X veya hücre simgesini seç ( [  ] ) ve sadece **X** ye bas.

* Yapıştırma yapmak için Ctrl+V veya hücre simgesini seç ( [  ] ) ve sadece **V** ye bas.


* **Hücreye tıklayıp + Shift** seçiliyken seçilen hücreyle tıklanan hücre arasındaki tüm hücreler seçilmiş olur.

* Hücreyi seçip iki defa **d** ye basarak hücre silinir.(D+D / d+d)

* Başlık oluşturmak için title başına (#) işareti konulur ve çalıştırılır.


* Alt başlık yapmak için (##) işareti konulur ve işaretlenir. (#,##,### vs. başlıklara göre kullanılabilir.

* Kodu çalıştırmak için üst şablondaki run tuşu veya shift+enter yapılır.

* Maddeleme işlemi için * işareti konulur.

# NumPy

In [4]:
a=[1,2,3,4]
b=[2,3,4,5]
a
b

[2, 3, 4, 5]

Hücrede **en son** neyi istiyorsak çıktı olarak onun sonucunu verir.

In [5]:
a

[1, 2, 3, 4]

In [2]:
import numpy as np

Kütüphaneler import ile dahil edilir.
Numpy kütüphanesini np kısayolu ile programımıza dahil ettik.
Optimizasyon ve yazılımsal anlamda veri saklamada daha iyidir.
High level bir dil, vektörel ve nümerik hesaplamaları rahatça yapılır.
Python listeleriyle kıyaslanırsa Numpy listelerinde tek tip veriler saklanabilir.

In [3]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])

In [8]:
a*b

array([ 2,  6, 12, 20])

 * Matrislerde nokta çarpımı yapmak için dot fonksiyonu kullanılır.

In [7]:
nok_çarp = np.dot(a,b)

In [9]:
nok_çarp

40

# NumPy Array'i Oluşturmak

In [10]:
import numpy as np 

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
a = np.array([1,2,3,4,5])

In [13]:
type(a)

numpy.ndarray

In [14]:
np.array([3.14, 4, 2, 13])

array([ 3.14,  4.  ,  2.  , 13.  ])

Numpy değişkenlerin aynı türe sabitlemek için hepsini ondalıklı olarak tek bir şekilde yazdı.

In [16]:
np.array([3.14, 4, 2, 13], dtype="float32")

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

Ama istersek float veya int olmasını biz belirleyebiliriz.

In [17]:
np.array([3.14, 4, 2, 13], dtype="int")

array([ 3,  4,  2, 13])

## Sıfırdan Array Oluşturma

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

10 tane 0 lardan oluşan sayılar

In [21]:
np.zeros(10, dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3,5),dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

3x5 lik matris olacak şekilde 1 lerden oluşan array

In [24]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])


Boyutu biz belirleyebiliyoruz.

 * (3,5) 3x5 lik boyut

 * 3 ifadesi ise bizim hangi sayılardan oluşmasını istediğimize göre değiştirilebilir.

In [26]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

**ÖNEMLİ** _0 dan 31 e kadar_ (31 dahil değil) 3 er 3 er ilerleme

 * ( _, _, _ ) = (Başlangıç Değeri, Son değer, Adım Sayısı)

In [27]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

0 ile 1 arasında 10 tane değer oluşturma 

In [28]:
np.random.normal(10,4,(3,4))

array([[ 8.71383526,  8.40929595,  7.54521322,  6.91027681],
       [11.07223263,  6.68558039,  8.28317793, 14.4018861 ],
       [ 9.04871848, 11.32053486, 17.41079866,  8.28323973]])

**ÖNEMLİ** Ortalama ,standart sapma, array boyutu belirleme 

 * (10,4,(3,4)) = (Ortalama, Standart Sapma, (Array Boyutu))

In [29]:
np.random.randint(0,10,(3,3))

array([[2, 4, 5],
       [6, 5, 3],
       [3, 2, 7]])

**ÖNEMLİ** İnteger değerlerle yapmak istersek bu fonksiyon kullanılır.

# ÖZELLİKLERİ

* **ndim**: boyut bilgisi
* **shape**: şekil bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [31]:
import numpy as np

In [33]:
np.random.randint(10, size = 10)

array([5, 2, 8, 9, 6, 1, 7, 2, 8, 2])

In [34]:
a = np.random.randint(10, size = 10)

In [35]:
a.ndim

1

In [36]:
a.shape

(10,)

In [37]:
a.size

10

In [38]:
a.dtype

dtype('int32')

In [78]:
b = np.random.randint(10, size = (3,5))

In [79]:
b

array([[5, 6, 4, 7, 4],
       [4, 5, 0, 2, 3],
       [2, 7, 3, 2, 8]])

In [80]:
b.ndim

2

In [81]:
b.shape

(3, 5)

In [43]:
b.size

15

In [45]:
b.dtype

dtype('int32')

## Yeniden Şekillendirme (Reshaping)

In [1]:
import numpy as np 

In [2]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**ÖNEMLİ** Tek boyuttan iki veya üç boyuta ya da  çok boyuttan tek boyuta geçmek için kullanılır.

In [5]:
a = np.arange(1,10)

In [6]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a.ndim

1

In [9]:
b = a.reshape ((1,9))

In [10]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [11]:
b.ndim 

2

[ ] sayısı boyut sayısını verir

 * İlk örnekte (a) 1 tane [ ] kullanıldı. Tek boyutlu olduğunu gösterir.

 * İkinci örnekte (b) 2 tane [ ] kullanıldı. 2 boyutlu olduğunu gösterir.


## Array Birleştirme (Concatenation)

In [13]:
import numpy as np 

In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [15]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [16]:
z = np.array([7,8,9])

In [17]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### İki Boyut

In [19]:
a = np.array([[1,2,3],
             [4,5,6]])

Matrisi kendisiyle birleştirmek için ;


In [20]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

**ÖNEMLİ**  _axis_ komutu 

0 ise sütun olarak

1 ise satır olarak birleştirme yapar.

In [21]:
np.concatenate([a,a], axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [22]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

Yapısı bilinen verileri ayırmada kullanılır.

In [24]:
import numpy as np 

In [28]:
x =  np.array([1,2,3,99,99,3,2,1])

In [29]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

x =  np.array([1,2,3,99,99,3,2,1]) serisinde 1,2,3 ü ve 3,2,1 serilerilerini 99,99 kısmından ayırmak istiyoruz.

İndexlemeyle ( [3,5] );

* 0 dan 3 e kadar olanları ayırdı.
* 3 ten 5 e kadar olanları ayırdı.
* Sonrası için ayrıca bir index kullanmaya gerek yoktur. 

**Ayrıca [3,5] şeklinde iki index belirttiğimiz için 1 fazlası kadar gruba ayırdı.**

3 index belirtseydik 4 grup oluşurdu.

Eğer bu çıktıları kullanmak için direkt bir atama işlemi gerekirse 3 grup için örneğin a,b,c şeklinde atama yapılır.

In [30]:
a,b,c = np.split(x, [3,5])

In [31]:
a

array([1, 2, 3])

In [32]:
b

array([99, 99])

In [33]:
c

array([3, 2, 1])

### İki Boyutlu Ayırma 

In [35]:
m = np.arange(16).reshape(4,4)

In [36]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

16 ya kadar sayıları 4x4 e olacak şekilde matris şeklide yazdırdık.

**_HATIRLATMA_**          
**arange fonksiyonu** bir sayıya kadar ritmik veya ardışık sayma işlemi yapıyordu.



#### **ÖNEMLİ**

  * Satır olarak ayırmak için **vsplit**

  * Sütun olarak ayırmak için **hsplit**

In [37]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

Matrisi satırda (0 ve 1.satırlar) 2.indexe göre ayırdı ve 2 grup oluşturup yanına yazdı.

Dikey olarak yan yana koyma işlemi yapıyor.

In [38]:
ust,alt = np.vsplit(m,[2])

In [39]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

Matrisi sütunda (0,1,2 ye kadar) 2.indexe göre ayırdı ve 2 grup oluşturup yanına yazdı.


In [46]:
sag,sol = np.hsplit(m,[2])

In [47]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [48]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Sıralama (Sorting) 

In [50]:
import numpy as np

In [51]:
v = np.array([2,1,4,3,5])

In [52]:
v

array([2, 1, 4, 3, 5])

In [53]:
np.sort(v)

array([1, 2, 3, 4, 5])

 * Rastgele olan diziyi **küçükten büyüğe** sıralama yaptı.


In [54]:
v

array([2, 1, 4, 3, 5])

 * v.sort ifade **ölümcül yan etkili** metodlardandır.

 * Sıralamayı yaptı ve diziyi sıralamadaki haliyle kaydetti.

 * Dizinin yapısını tamamen bozup,değiştirdi.


In [55]:
v.sort()

In [56]:
v

array([1, 2, 3, 4, 5])

In [57]:
np.sort(v)

array([1, 2, 3, 4, 5])

### İki Boyutlu Array Sıralama

Ortalaması 20, standart sapması 5 olan 3x3 lük bir rastgele matris oluşturduk.

In [60]:
m = np.random.normal(20,5, (3,3))

In [61]:
m

array([[14.88585978, 18.72688424, 18.61844291],
       [21.34397727, 18.54969049, 23.50303132],
       [27.54709025, 23.68563315, 15.24476114]])

Arrayin satırlarını sıralamak için;

 * Her bir satırı kendi içinde küçükten büyüğe sıraladı. axis = 1

 * Her bir sütunu kendi içinde küçükten büyüğe sıraladı. axis = 0

In [62]:
np.sort(m, axis = 1)

array([[14.88585978, 18.61844291, 18.72688424],
       [18.54969049, 21.34397727, 23.50303132],
       [15.24476114, 23.68563315, 27.54709025]])

In [64]:
np.sort(m, axis = 0)

array([[14.88585978, 18.54969049, 15.24476114],
       [21.34397727, 18.72688424, 18.61844291],
       [27.54709025, 23.68563315, 23.50303132]])

### Array Sıralama (Sorting)

In [66]:
import numpy as np

In [67]:
v = np.array([2,1,4,3,5])

In [68]:
v

array([2, 1, 4, 3, 5])

In [69]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [70]:
v

array([2, 1, 4, 3, 5])

In [71]:
v.sort()

In [72]:
v

array([1, 2, 3, 4, 5])

### İki  Boyutlu Array Sıralama 

In [73]:
m = np.random.normal(20,5, (3,3))

In [74]:
m

array([[28.71108595, 22.72115657, 26.14587578],
       [15.43583279, 19.67078799, 25.03781274],
       [15.3783379 , 24.54100318, 14.46224367]])

In [78]:
np.sort(m, axis = 1)

array([[22.72115657, 26.14587578, 28.71108595],
       [15.43583279, 19.67078799, 25.03781274],
       [14.46224367, 15.3783379 , 24.54100318]])

In [79]:
np.sort(m, axis = 0)

array([[15.3783379 , 19.67078799, 14.46224367],
       [15.43583279, 22.72115657, 25.03781274],
       [28.71108595, 24.54100318, 26.14587578]])

## Index İle Elemanlara Erişmek 

In [81]:
import numpy as np 
a = np.random.randint(10, size = 10)
a

array([9, 7, 7, 5, 1, 9, 9, 4, 2, 3])

 * 10 a kadar olan sayılardan 10 elemanlı bir array oluşturduk.

In [82]:
a[0]

9

In [83]:
a[-1]

3

In [84]:
a[0] = 100

In [85]:
a

array([100,   7,   7,   5,   1,   9,   9,   4,   2,   3])

In [86]:
m = np.random.randint(10, size = (3,5))
m

array([[4, 8, 8, 8, 7],
       [7, 9, 4, 0, 2],
       [4, 6, 9, 1, 7]])

 * 10 a kadar olan sayılardan 3x5 boyutunda olacak şekilde array oluşturdu.

 * m[i,j]
    
    i: satır sayısı
    j:sütun sayısı
    
   m[2,3] = 2.satır 3.sütundaki eleman (1)

In [87]:
m[0,0]

4

In [88]:
m[1,0]

7

In [89]:
m[1,1]

9

In [90]:
m[1,4]

2

In [91]:
m[1,4] = 99

In [92]:
m

array([[ 4,  8,  8,  8,  7],
       [ 7,  9,  4,  0, 99],
       [ 4,  6,  9,  1,  7]])

In [93]:
m[1,4] = 2.2

In [94]:
m

array([[4, 8, 8, 8, 7],
       [7, 9, 4, 0, 2],
       [4, 6, 9, 1, 7]])

## Slicing İle Eleman Erişmek (Array Alt Kümesine Erişmek)

In [95]:
import numpy as np 

In [96]:
a = np.arange(20,30)

In [97]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

 * [n:m]  =   n. elemandan başlayıp m ye kadar olan elemanlar (m dahil değildir).

In [98]:
a[0:3]

array([20, 21, 22])

In [99]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [100]:
a[:3]

array([20, 21, 22])

In [101]:
a[1::2]

array([21, 23, 25, 27, 29])

In [102]:
a[0::2]

array([20, 22, 24, 26, 28])

In [103]:
a[2::2]

array([22, 24, 26, 28])

In [104]:
a[0::3]

array([20, 23, 26, 29])

### İki Boyutlu Slice İşlemleri

In [105]:
m = np.random.randint(10, size =(5,5))

In [106]:
m

array([[8, 9, 7, 5, 2],
       [7, 1, 0, 0, 1],
       [2, 0, 9, 8, 5],
       [9, 8, 6, 6, 9],
       [8, 2, 7, 8, 3]])

 * Bütün satırları ve 0. sütunu seçeceğiz.

In [107]:
m[:,0]

array([8, 7, 2, 9, 8])

 * Bütün satırları ve 1. sütunu seçeceğiz.

In [109]:
m[:,1]

array([9, 1, 0, 8, 2])

 * 0. satır ve bütün sütunları seçeceğiz.

In [110]:
m[0,:]

array([8, 9, 7, 5, 2])

In [111]:
m[0]

array([8, 9, 7, 5, 2])

In [112]:
m[1,:]

array([7, 1, 0, 0, 1])

 * 0 dan 2 ye kadar olan satırlar ile 0 dan 3 e kadar olan sütunları seçeceğiz.

In [113]:
m[0:2,0:3]

array([[8, 9, 7],
       [7, 1, 0]])

In [114]:
m[::,:2]

array([[8, 9],
       [7, 1],
       [2, 0],
       [9, 8],
       [8, 2]])

In [115]:
m[:,0:2]

array([[8, 9],
       [7, 1],
       [2, 0],
       [9, 8],
       [8, 2]])

In [117]:
m

array([[8, 9, 7, 5, 2],
       [7, 1, 0, 0, 1],
       [2, 0, 9, 8, 5],
       [9, 8, 6, 6, 9],
       [8, 2, 7, 8, 3]])

In [116]:
m[1:3,0:2]

array([[7, 1],
       [2, 0]])

## Alt Küme Üzerinde İşlem Yapmak 

In [119]:
import numpy as np 
a = np.random.randint(10, size = (5,5))
a

array([[2, 4, 8, 1, 6],
       [9, 7, 6, 8, 5],
       [8, 3, 7, 7, 0],
       [9, 2, 9, 6, 2],
       [2, 9, 8, 8, 9]])

In [120]:
alt_a = a[0:3,0:2]

In [121]:
alt_a

array([[2, 4],
       [9, 7],
       [8, 3]])

In [122]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [123]:
alt_a

array([[99999,     4],
       [    9,   888],
       [    8,     3]])

In [124]:
m = a = np.random.randint(10, size = (5,5))
m

array([[7, 8, 4, 6, 8],
       [4, 9, 0, 0, 8],
       [6, 7, 5, 5, 7],
       [3, 7, 7, 4, 6],
       [6, 3, 6, 8, 4]])

 * Array üzerindeki belli bir kısımda işlem yapmak istersek sadece gerekli olan kısmı almak için copy fonksiyonu kullanaraktan işlemler yapılabillir.
 * Gerçek dizi üzerinde herhangi bir değişikliğe sebep olmaz.

In [125]:
alt_b = m[0:3,0:2].copy()

In [126]:
alt_b

array([[7, 8],
       [4, 9],
       [6, 7]])

In [127]:
m

array([[7, 8, 4, 6, 8],
       [4, 9, 0, 0, 8],
       [6, 7, 5, 5, 7],
       [3, 7, 7, 4, 6],
       [6, 3, 6, 8, 4]])

#### **ÖNEMLİ!**         

### _**TEKRARDAN!**_

**copy** komutuyla asıl veride değişiklik yapmadık.

Sadece aldığımız kısmında değişiklik yaptık. Asıl veriyi etkilemedi.


In [128]:
alt_b[0,0] = 9999

In [129]:
alt_b

array([[9999,    8],
       [   4,    9],
       [   6,    7]])

In [130]:
alt_b*3

array([[29997,    24],
       [   12,    27],
       [   18,    21]])

In [131]:
m

array([[7, 8, 4, 6, 8],
       [4, 9, 0, 0, 8],
       [6, 7, 5, 5, 7],
       [3, 7, 7, 4, 6],
       [6, 3, 6, 8, 4]])

## (öNEMLİ) Fancy Index İle Elemanlara Erişmek  

In [4]:
import numpy as np 

In [133]:
v = np.arange(0,30,3)

In [134]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [135]:
v[1]

3

In [136]:
v[3]

9

In [137]:
v[5]

15

In [139]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [140]:
al_getir = [1,3,5]

 * Bir dizi veya döngü içinden almamız gereken verilerin indexlerinin listeleyerek çekeriz. 

 * Böylece tek tek veri almaktan kurtulmuş olunur. 

 * Bu yapılan işleme **fancy** denilmektedir.

 * Çok sık kullanılan önemli bir işlevdir.

In [141]:
v[al_getir]

array([ 3,  9, 15])

### İki Boyutta Fancy 

In [5]:
m = np.arange(9).reshape((3,3))

In [6]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
satir = np.array([0,1])
sutun = np.array([1,2]) 

In [8]:
m[satir,sutun]

array([1, 5])

### Basit Index İle Fancy Index

In [9]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
m[0,[1,2]]

array([1, 2])

### Slice ile fancy

In [16]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [17]:
import numpy as np 

In [18]:
v = np.array([1,2,3,4,5])

In [19]:
v>5

array([False, False, False, False, False])

In [20]:
v<3

array([ True,  True, False, False, False])

**ÖNEMLİ**  Koşulları sağlayanlar True sağlamayanlar False çıktısı verir.

Burada Fancy i kullanabiliriz.

Koşulu index içine yazarak bu koşulu sağlayan elemanları direkt çıktı olarak bize verir.


In [21]:
v[v<3]

array([1, 2])

In [22]:
v[v>3]

array([4, 5])

In [23]:
v[v>=3]

array([3, 4, 5])

In [24]:
v[v<=3]

array([1, 2, 3])

In [25]:
v[v==3]

array([3])

In [26]:
v[v!=3]

array([1, 2, 4, 5])

In [27]:
v

array([1, 2, 3, 4, 5])

In [28]:
v * 2 

array([ 2,  4,  6,  8, 10])

In [29]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [30]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [31]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

## Matematiksel İşlemler

In [34]:
import numpy as np 

In [35]:
v = np.array([1,2,3,4,5])

In [37]:
v - 1

array([0, 1, 2, 3, 4])

In [38]:
v * 5

array([ 5, 10, 15, 20, 25])

In [39]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [40]:
v*5/10 -1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

### ufunc

In [42]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [43]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [44]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [45]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [47]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [48]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [49]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [50]:
np.absolute(np.array([-3]))

array([3])

In [51]:
np.sin(360)

0.9589157234143065

In [52]:
np.cos(180)

-0.5984600690578581

In [53]:
v = np.array([1,2,3,])

In [54]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [55]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [56]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [57]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\User\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\user\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [58]:
#cheatsheet

# İstatiksel Hesaplamalar

In [61]:
v

array([1, 2, 3])

In [60]:
np.mean(v,axis=0)

2.0

In [62]:
v.sum()

6

In [63]:
v.min()

1

 
np.mean(arr,axis=0) | Returns mean along specific axis

arr.sum() | Returns sum of arr

arr.min() | Returns minimum value of arr

arr.max(axis=0) | Returns maximum value of specific axis

np.var(arr) | Returns the variance of array

np.std(arr,axis=1) | Returns the standard deviation of specific axis

arr.corrcoef() | Returns correlation coefficient of array

## Numpy İle İki Bilinmeyenli Denklem Çözümü

In [67]:
import numpy as np 

5 * x0 + x1 = 12

0 + 3 * x1 = 10

 * x0 ve x1 in katsayılarını ve çıkan sonuçları ayrı değerlere atayıp. x0 ve x1 köklerini bulmak için linalg fonksiyonu kullanılır.

In [72]:
a = np.array([[5,1],[1,3]])
b = np. array([12,10])

In [73]:
a

array([[5, 1],
       [1, 3]])

In [74]:
b

array([12, 10])

In [75]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

Lineer cebir için bir paket: x0 ve x1 değerlerini bulur